### ISSUE TITLE
bad 2.2.1 SHA256SUMS.txt.asc signature

### ISSUE THREAD

**Issue by bughit** [Genymobile/gnirehtet#102]
```
gpg: assuming signed data in 'SHA256SUMS.txt'
gpg: Signature made 03/13/18 12:09:01 Eastern Daylight Time
gpg:                using DSA key 86E43F4E340BCCE18566719A72FCC14D644605F3
gpg: BAD signature from "Romain Vimont (®om) <rom@rom1v.com>" [unknownn]
```

2.2.0 is ok

**Comment by rom1v** [comment]
Thank you for your vigilance! :+1:

Indeed, the signature was incorrect, even locally (the files I generated before uploading to github). This is probably because I first prepared a release, then applied a minor change and regenerated the files, but forgot to resign the sha256sums.

The SHA256 sums are correct, though (they match the files I initially generated. So I just signed that file and replaced the wrong one.
