### ISSUE TITLE
Can I communicate host => phone?

### ISSUE THREAD

**Issue by valgusk** [Genymobile/gnirehtet#105]
Is it possible to eg. ping the phone with this connection? Or is it completely inaccessible from the host OS?

**Comment by rom1v** [comment]
Every input event (keyboard and mouse) sends an event from the host to the device, so the host communicates with the device. What do you want to do exactly?

**Comment by valgusk** [comment]
OK, I am confused. Since I do not understand the answer, the question must have been very stupid. Sorry about that and please delete/close the issue

**Comment by rom1v** [comment]
> I do not understand the answer

That's probably because I did not understand the question. This does not imply that the question is stupid :)

What do you want to do?

**Comment by PhilLab** [comment]
@rom1v it looks like your answer is more true to https://github.com/Genymobile/scrcpy , not to this project here, though quite related. I think I have the same question as @valgusk so I will try to elaborate:

**Comment by rom1v** [comment]
> it looks like your answer is more true for https://github.com/Genymobile/scrcpy , not to this project here, though quite related.

Ah, that's why I did not understand the question. Sorry @valgusk! Thank you for explaining @PhilLab :wink: 

> At which ip can my host machine reach the Android device?

It can't directly, they're not on the "same network".

If you want to reach a specific port on the device, you need to enable adb port forwarding. For example:

    adb forward tcp:1234 tcp:5678

Then, from your host, when you connect to `localhost:1234`, it will connect to the device on port 5678.

> But it does work over WiFi.

Yes, that's expected.

**Comment by rom1v** [comment]
Note that it is also possible to _reverse tether_ only specific routes. For example:

    ./gnirehtet start -r 8.8.8.8,192.168.0.0/24

Only 8.8.8.8 and 192.168.0.* will be _reverse tether_, the others will use the device connection normally.

**Comment by KeithScheiwiller** [comment]
@rom1v Sorry for bumping this old issue. Just a quick question on this. Would it be technically feasible to tweak gnirehtet so that it _is_ bidirectional? In other words, could the host and phone be made to be on the same "network"?

If it is possible, I might look into implementing it. But I'm not completely sure how gnirehtet actually works, so it might actually not even be possible. Thanks!

**Comment by rom1v** [comment]
> In other words, could the host and phone be made to be on the same "network"?

No, I don't think so.
