### ISSUE TITLE
Log File collection

### ISSUE THREAD

**Issue by Zero3K** [Genymobile/gnirehtet#13]
I am attaching my log file to see if it can help fix any issues with it. If anyone else has one, feel free to attach it in a comment.

[gnirehtet log.zip](https://github.com/Genymobile/gnirehtet/files/908527/gnirehtet.log.zip)

**Comment by ewoks** [comment]
## Please DON'T, here is why:
This issue is useless. 
It is pointless to collect log files under one "issue ticket" that doesn't actually describe any specific issue. It is making developer's and contributor's job more difficult and that shouldn't be the goal.

If you have some specific problem/bug and you think log file would help for that specific problem it makes sense to open issue, describe desired (expected) behaviour, describe actual behaviour, and attach **focused** log so developers can immediately (or at least fast) scan through it and eventually pinpoint the part that helps to resolve the issue. 

Adding bunch of logs with 4000+ lines not related to any description is just making **noise**.

_Lets not make facebook feed from github..._

**Comment by rom1v** [comment]
Your logs look normal. No specific issue here. I'm closing.
