### ISSUE TITLE
Google Play Store

### ISSUE THREAD

**Issue by Zero3K** [Genymobile/gnirehtet#14]
I think it should be put on there so that way more people will be using it. All that would need to be changed is the inclusion of a GUI that tells the user to download and run the relay server on his/her PC with a link to it (and possibly statistics of the connection) in the app.

**Comment by ewoks** [comment]
It is decision of developer if he needs to put it to play store, not real issue. 

Project is open source, so anybody can fork and modify (add code, remove code, write app) under license agreement and he is good to go. That includes you @Zero3K as well as anybody else.

In my opinion issue should be closed because it is just making unnecessary noise not related to actual functionality of the project but business decision.

**Comment by rom1v** [comment]
Publishing it to the Play store provides no "functional" benefit, since the user need to execute commands from the desktop anyway (`./gnirehtet rt` installs the app if necessary).

However, this may provide some "marketing" benefits (so that users may find the application by searching "reverse tethering" on Google Play). As we discussed internally, there is a possibility that we decide to implement some "wizard" activity on the device to explain how to use it from the computer. I still think this is weird (the activity would provide no feature), but maybe…

Anyway, as suggested by @ewoks, this is not an issue. I close it.
