### ISSUE TITLE
Gnirehtet leaking connections and memory on TCP misuse 

### ISSUE THREAD

**Issue by artnalban** [Genymobile/gnirehtet#57]
Not sure if this is even important to you, but I have noticed that gnirehtet leaking connection and memory when trying to do TCP connections when UDP is required. I had to write internet connectivity checker, so I was trying to ping Google public DNS. Later turned out that I was trying to establish TCP connections instead of UDP. 
In order to repro this run this in a loop:
```java
Socket sock = new Socket();
SocketAddress sockaddr = new InetSocketAddress("8.8.8.8", 53);

sock.connect(sockaddr , timeoutMs);
sock.close();
```

Overtime time this will cause connections and memory to leak. This repros on both java and rust relay server implementations.

**Comment by rom1v** [comment]
Thank you for your report.

> Not sure if this is even important to you

Of course, it is :)

> I have noticed that gnirehtet leaking connection and memory when trying to do TCP connections when UDP is required

In fact, it affects all TCP sockets : a `close()` from the Android-side left the TCP connection state in a "waiting state" indefinitely, which is quite a huge bug. Google DNS also listens on TCP, that's why you get the problem with it.

I just fixed it on `dev` branch. Could you test, please?

**Comment by artnalban** [comment]
Hello, I've quickly tested java relay server today and haven't seen any connection to stack up. I was unable to test rust implementation because I couldn't build it.

Thanks.

**Comment by rom1v** [comment]
It's in the v2.2 release: https://github.com/Genymobile/gnirehtet/releases/tag/v2.2
