### ISSUE TITLE
Batch files, etc. to launch it hidden with the output redirected to a log file

### ISSUE THREAD

**Issue by Zero3K** [Genymobile/gnirehtet#7]
I have made a ZIP file containing the files needed for it to do what I wrote about in the title and am attaching it to this issue. You can modify the batch files accordingly. I hope it helps :).

EDIT: I am replacing it with a better version.

[gnirehtet.zip](https://github.com/Genymobile/gnirehtet/files/908848/gnirehtet.zip)

**Comment by Zero3K** [comment]
I made a slight change to the main batch file. I am attaching it now.

[gnirehtet batch file.zip](https://github.com/Genymobile/gnirehtet/files/907858/gnirehtet.batch.file.zip)

**Comment by rom1v** [comment]
Hi,

Thank you for your work.

I am very interested by a `gnirehtet.bat` with the same behavior as the `gnirehtet` _bash_ script. It seems you know the BATCH syntax well, do you think it's possible?

I guess your current scripts may be convenient on windows because you can double-click on `relay.bat`, then "double-click" on `gnirehtet.bat`, instead of calling a script with arguments. However, with a `gnirehtet.bat` similar to the existing bash, those scripts might just delegate the work to `gnirehtet.bat` with the expected arguments.

What do you think?

**Comment by Zero3K** [comment]
I am not that knowledgeable in making batch files. Anyways, the only batch that needs running is gnirehtet.bat since it runs relay.bat via JStart (which is used to hide the console that relay.jar uses).

**Comment by rom1v** [comment]
OK. Thank you for the samples.

However, they are too specific (`jre1.8.0_112`, `C:`Program Files\gnirehtet`…), and they use binaries that I would not include (`jStart.exe`, `adb.exe`, `*.dll`…).

But thanks, that may help some people on Windows willing to use it the same way.

If you manage to implement a generic `gnirehtet.bat` similar to the bash script, please open a PR ;)

**Comment by MegaZeroX10** [comment]
How do I get the batch to not show "Error: Not found; no service started."?
