### ISSUE TITLE
GUI for Windows and Linux

### ISSUE THREAD

**Issue by Zero3K** [Genymobile/gnirehtet#8]
It would be nice if one was made so that way I don't have to use batch files in order to have it be running.

**Comment by ewoks** [comment]
too biased and personal preference in my opinion. Why not macOS too?!
The main purpose of tool is not to make more windows, so IF at all this will be implemented ever I would put it on the lowest priority ever because it requires a lot of work for little convenience. Current approach with batch files is more than simple for beginner user.

**Comment by rom1v** [comment]
I have not planned to implement any graphical UI for this tool.

If some people want a GUI, they may implement it. In that case, I suggest that _gnirehtet_ should not depend on it, so that it may still run in a "headless" environment (i.e. without graphical display, so no X server, etc.).
